---
all:
  children:
    webservers:   
      hosts:
        server1:
          ansible_host: 172.17.0.2
          ansible_port: 22
          ansible_password: 123456
          ansible_become_password: 123456 
        server2:
          ansible_host: 172.17.0.3
          ansible_port: 22
          ansible_password: 123456
          ansible_become_password: 123456