---
- name: Configure webserver with Nginx and TLS
  hosts: webservers
  become: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost

  handlers:
    - name: restart nginx
      shell: |
        nginx -s reload

  tasks:
    - name: Check whether Nginx service start or not
      stat:
        path: /var/run/nginx.pid
      register: nginx_pid_file

    - name: Install Nginx
      apt:
        name: nginx
        update_cache: yes
        cache_valid_time: 3600
      when: not nginx_pid_file.stat.exists

    - name: Start Nginx
      shell: |
        nginx
      when: not nginx_pid_file.stat.exists
    
    - name: Create directories for ssl certificates
      file:
        path: /etc/nginx/ssl
        state: directory
    
    - name: Copy TLS key
      copy:
        src: files/nginx.key
        dest: "{{ key_file }}"
        owner: root
        mode: 0600
      notify: restart nginx
    
    - name: Copy TLS certicate
      copy:
        src: files/nginx.crt
        dest: "{{ cert_file }}"
      notify: restart nginx
    
    - name: Copy nginx config file
      template:
        src: templates/nginx.conf.j2
        dest: "{{ conf_file }}"
      notify: restart nginx
    
    - name: Enable configuration
      file:
        dest: /etc/nginx/sites-enabled/default
        src: "{{ conf_file }}"
        state: link
      notify: restart nginx
    
    - name: Copy index.html
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: 0644

      